### ISSUE TITLE
npx usage

### ISSUE THREAD

**Issue by dasa** [azz/pretty-quick#47]
Running `npx pretty-quick` errors with "Cannot find module 'prettier'".

This works though: `npx -p prettier -p pretty-quick pretty-quick`

**Comment by azz** [comment]
Good catch. Maybe it's better to recommend `npm i prettier pretty-quick` before `npx pretty-quick `

**Comment by RonanCodes** [comment]
Interestingly this issues pops up when you try to upgrade an Angular project to an NX project:
```yaml
$ npx make-angular-cli-faster       
npx: installed 240 in 24.982s

>  NX  Nx initialization

Cannot find module 'prettier'
Require stack:
- /Users/X/dev/projects/nx/ng-app/node_modules/@nrwl/workspace/src/utilities/prettier.js
- /Users/X/dev/projects/nx/ng-app/node_modules/@nrwl/workspace/src/generators/init/init.js
- /Users/X/dev/projects/nx/ng-app/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/X/dev/projects/nx/ng-app/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/X/dev/projects/nx/ng-app/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/X/dev/projects/nx/ng-app/node_modules/@nrwl/tao/src/commands/generate.js
- /Users/X/dev/projects/nx/ng-app/node_modules/@nrwl/tao/index.js
- /Users/X/dev/projects/nx/ng-app/node_modules/@nrwl/cli/lib/init-local.js
- /Users/X/dev/projects/nx/ng-app/node_modules/@nrwl/cli/bin/nx.js
Error: Command failed: nx g @nrwl/workspace:ng-add --preserveAngularCLILayout
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at /Users/X/.npm/_npx/28007/lib/node_modules/make-angular-cli-faster/make-angular-cli-faster.js:61:25
    at Generator.next (<anonymous>)
    at /Users/X/.npm/_npx/28007/lib/node_modules/make-angular-cli-faster/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/X/.npm/_npx/28007/lib/node_modules/make-angular-cli-faster/node_modules/tslib/tslib.js:113:16)
    at main (/Users/X/.npm/_npx/28007/lib/node_modules/make-angular-cli-faster/make-angular-cli-faster.js:54:20)
    at Object.<anonymous> (/Users/X/.npm/_npx/28007/lib/node_modules/make-angular-cli-faster/make-angular-cli-faster.js:80:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 28699,
  stdout: null,
  stderr: null
}
```

After running your mentioned command:
```yaml
npx -p prettier -p pretty-quick pretty-quick
```

I can then run my command successfully:
```yaml
$ npx make-angular-cli-faster

...

>  NX   SUCCESS  Angular CLI is faster now!   
```
